version: "3.8"

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app_youcode
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - database
    command: ["/bin/sh", "-c", "composer install && apache2-foreground"]
    networks:
      - app_network

  database:
    image: postgres:15
    container_name: postgres_db_youcode
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_v2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - database
networks:
  app_network:

volumes:
  postgres_data:
  
